// GENERATED by `pnpm art:build` from /art — do not edit by hand.

export const ICON_ATLAS = {
  "src": "/icons/icons.png",
  "size": 16,
  "columns": 8,
  "sheetSize": {
    "w": 128,
    "h": 48
  },
  "names": [
    "quest-main",
    "quest-daily",
    "quest-side",
    "quest-boss",
    "quest-hidden",
    "stat-int",
    "stat-foc",
    "stat-vit",
    "stat-soc",
    "stat-cre",
    "ui-adventure",
    "ui-quests",
    "ui-gm",
    "ui-calendar",
    "ui-character",
    "ui-settings",
    "ui-sword",
    "ui-check",
    "ui-plus",
    "ui-close"
  ]
} as const;

export const GLYPH_ATLAS = {
  "src": "/icons/glyphs.png",
  "size": 8,
  "columns": 2,
  "sheetSize": {
    "w": 16,
    "h": 8
  },
  "names": [
    "star",
    "star-empty"
  ]
} as const;

export type IconName = (typeof ICON_ATLAS.names)[number];
export type GlyphName = (typeof GLYPH_ATLAS.names)[number];
