// GENERATED by `pnpm art:build` from /art — do not edit by hand.

export const SCENE_SPRITES = {
  "quest-board": {
    "src": "/sprites/scene/quest-board.png",
    "w": 32,
    "h": 32
  },
  "lantern": {
    "src": "/sprites/scene/lantern.png",
    "w": 16,
    "h": 32
  },
  "moon": {
    "src": "/sprites/scene/moon.png",
    "w": 16,
    "h": 16
  },
  "bush": {
    "src": "/sprites/scene/bush.png",
    "w": 16,
    "h": 16
  },
  "ground": {
    "src": "/sprites/scene/ground.png",
    "w": 16,
    "h": 16
  },
  "quest-marker": {
    "src": "/sprites/scene/quest-marker.png",
    "w": 16,
    "h": 16
  }
} as const;

export type SceneSpriteName = keyof typeof SCENE_SPRITES;
