// GENERATED by `pnpm art:build` from /art — do not edit by hand.

/** Frames left to right: idle, bob (idle 2), defeated, hit (white flash). */
export const MONSTER_SHEETS = {
  "slime": {
    "src": "/sprites/monsters/slime.png",
    "w": 24,
    "h": 24,
    "frames": 4
  },
  "tome": {
    "src": "/sprites/monsters/tome.png",
    "w": 24,
    "h": 24,
    "frames": 4
  },
  "watcher": {
    "src": "/sprites/monsters/watcher.png",
    "w": 24,
    "h": 24,
    "frames": 4
  },
  "ghost": {
    "src": "/sprites/monsters/ghost.png",
    "w": 24,
    "h": 24,
    "frames": 4
  },
  "wisp": {
    "src": "/sprites/monsters/wisp.png",
    "w": 24,
    "h": 24,
    "frames": 4
  },
  "dragon": {
    "src": "/sprites/monsters/dragon.png",
    "w": 32,
    "h": 32,
    "frames": 4
  }
} as const;

export type MonsterName = keyof typeof MONSTER_SHEETS;
