/**
 * Builds pixel-art sources in /art into shippable 1× PNG sheets + typed manifests.
 *
 *   pnpm art:build
 *
 * Outputs (all committed):
 *   public/sprites/characters/<id>-<preset>.png   one sheet per outfit preset (rows = states)
 *   public/icons/icons.png, public/icons/glyphs.png
 *   src/components/game/character/sprite-sheets.generated.ts
 *   src/components/pixel/icons.generated.ts
 *   src/app/icon.png                               32×32 favicon (head crop, 2×)
 *   public/icons/app-{192,512}.png, src/app/apple-icon.png   opaque app icons (PWA)
 *   art/palette/life-32.gpl                        Aseprite/GIMP palette
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { ADVENTURER } from "../../art/characters/adventurer";
import { GLYPHS, ICONS } from "../../art/icons";
import { LIFE_32, OUTFIT_PRESETS, type OutfitPreset } from "../../art/palette";
import { SCENE_SPRITES } from "../../art/scene";
import type { PixelGrid } from "../../art/types";
import { createCanvas, cropGrid, drawGrid, encodePng, padGrid, validateGrid } from "./lib";
import { OG_ALT, renderOgImage } from "./og";

const ROOT = join(import.meta.dirname, "..", "..");
const ICON_SIZE = 16;
const GLYPH_SIZE = 8;
const SHEET_COLUMNS = 8;
const GENERATED_HEADER = "// GENERATED by `pnpm art:build` from /art — do not edit by hand.\n";

function write(relativePath: string, contents: Buffer | string) {
  const path = join(ROOT, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  console.log(`  wrote ${relativePath}`);
}

/* ───────── Characters ───────── */

function buildCharacter() {
  const { id, frameSize, anchor, states } = ADVENTURER;
  const stateEntries = Object.entries(states);
  const maxFrames = Math.max(...stateEntries.map(([, s]) => s.frames.length));

  for (const [name, state] of stateEntries) {
    if (state.frames.length !== state.durations.length) {
      throw new Error(`${id}.${name}: frames and durations differ in length`);
    }
    state.frames.forEach((frame, i) => validateGrid(`${id}.${name}[${i}]`, frame, frameSize, true));
  }

  const images: Record<string, string> = {};
  for (const preset of Object.keys(OUTFIT_PRESETS) as OutfitPreset[]) {
    const canvas = createCanvas(frameSize.w * maxFrames, frameSize.h * stateEntries.length);
    stateEntries.forEach(([, state], row) => {
      state.frames.forEach((frame, col) =>
        drawGrid(canvas, frame, col * frameSize.w, row * frameSize.h, { preset }),
      );
    });
    const file = `/sprites/characters/${id}-${preset}.png`;
    write(join("public", file), encodePng(canvas));
    images[preset] = file;
  }

  const manifest = {
    id,
    frameSize,
    anchor,
    sheetSize: { w: frameSize.w * maxFrames, h: frameSize.h * stateEntries.length },
    images,
    states: Object.fromEntries(
      stateEntries.map(([name, s], row) => [
        name,
        {
          row,
          frames: s.frames.length,
          durations: s.durations,
          loop: s.loop,
          ...("next" in s && s.next ? { next: s.next } : {}),
        },
      ]),
    ),
  };

  write(
    "src/components/game/character/sprite-sheets.generated.ts",
    `${GENERATED_HEADER}
export const SPRITE_SHEETS = ${JSON.stringify({ [id]: manifest }, null, 2)} as const;

export type SpriteSheetId = keyof typeof SPRITE_SHEETS;
`,
  );

  // Favicon: head crop (rows 3–15, cols 9–22) centered in 16×16, rendered at 2×.
  const head = padGrid(cropGrid(states.idle.frames[0]!, 9, 3, 14, 13), 16, 16);
  const favicon = createCanvas(32, 32);
  drawGrid(favicon, head, 0, 0, { preset: "royal", scale: 2 });
  write("src/app/icon.png", encodePng(favicon));

  // App icons (PWA, home screen): the same head on an opaque ink-800 tile. The 16-unit head
  // sits in a 24-unit tile so it stays inside the maskable safe zone (central 80%).
  const tile = Array.from({ length: 24 }, () => "n".repeat(24));
  const appArt = head.reduce<string[]>(
    (rows, line, y) =>
      rows.map((row, ry) =>
        ry === y + 4
          ? row.slice(0, 4) +
            [...line].map((c, x) => (c === "." ? row[4 + x] : c)).join("") +
            row.slice(20)
          : row,
      ),
    tile,
  );
  for (const [file, size] of [
    ["public/icons/app-192.png", 192],
    ["public/icons/app-512.png", 512],
    ["src/app/apple-icon.png", 192],
  ] as const) {
    // Integer scale only; any remainder becomes an even ink-800 margin.
    const scale = Math.floor(size / 24);
    const offset = (size - 24 * scale) / 2;
    const canvas = createCanvas(size, size);
    drawGrid(
      canvas,
      Array.from({ length: size }, () => "n".repeat(size)),
      0,
      0,
    );
    drawGrid(canvas, appArt, offset, offset, { preset: "royal", scale });
    write(file, encodePng(canvas));
  }
}

/* ───────── Icons & glyphs ───────── */

function buildAtlas(
  label: string,
  entries: ReadonlyArray<readonly [string, PixelGrid]>,
  size: number,
  file: string,
) {
  entries.forEach(([name, grid]) => validateGrid(`${label}.${name}`, grid, { w: size, h: size }));
  const columns = Math.min(SHEET_COLUMNS, entries.length);
  const rows = Math.ceil(entries.length / columns);
  const canvas = createCanvas(columns * size, rows * size);
  entries.forEach(([, grid], i) =>
    drawGrid(canvas, grid, (i % columns) * size, Math.floor(i / columns) * size),
  );
  write(join("public", file), encodePng(canvas));
  return {
    src: file,
    size,
    columns,
    sheetSize: { w: columns * size, h: rows * size },
    names: entries.map(([name]) => name),
  };
}

function buildIcons() {
  const icons = buildAtlas("icon", Object.entries(ICONS), ICON_SIZE, "/icons/icons.png");
  const glyphs = buildAtlas("glyph", Object.entries(GLYPHS), GLYPH_SIZE, "/icons/glyphs.png");
  write(
    "src/components/pixel/icons.generated.ts",
    `${GENERATED_HEADER}
export const ICON_ATLAS = ${JSON.stringify(icons, null, 2)} as const;

export const GLYPH_ATLAS = ${JSON.stringify(glyphs, null, 2)} as const;

export type IconName = (typeof ICON_ATLAS.names)[number];
export type GlyphName = (typeof GLYPH_ATLAS.names)[number];
`,
  );
}

/* ───────── Scene props ───────── */

function buildScene() {
  const manifest: Record<string, { src: string; w: number; h: number }> = {};
  for (const [name, grid] of Object.entries(SCENE_SPRITES)) {
    const size = { w: grid[0]?.length ?? 0, h: grid.length };
    if (size.w % 16 !== 0 || size.h % 16 !== 0) {
      throw new Error(`scene.${name}: ${size.w}×${size.h} is not a multiple of the 16ap tile`);
    }
    validateGrid(`scene.${name}`, grid, size);
    const canvas = createCanvas(size.w, size.h);
    drawGrid(canvas, grid, 0, 0);
    const file = `/sprites/scene/${name}.png`;
    write(join("public", file), encodePng(canvas));
    manifest[name] = { src: file, ...size };
  }
  write(
    "src/components/pixel/scene-sprites.generated.ts",
    `${GENERATED_HEADER}
export const SCENE_SPRITES = ${JSON.stringify(manifest, null, 2)} as const;

export type SceneSpriteName = keyof typeof SCENE_SPRITES;
`,
  );
}

/* ───────── Open Graph background ───────── */

/**
 * 200×105ap night scene rendered at exactly 6× → 1200×630, so the OG image needs no
 * resampling. Text is drawn on top by src/app/opengraph-image.tsx.
 */
function buildOgScene() {
  const W = 200;
  const H = 105;
  const SCALE = 6;
  const rowsOf = (fill: string) => Array.from({ length: H }, () => fill.repeat(W).split(""));
  const scene = rowsOf("O");
  const stamp = (grid: PixelGrid, x: number, y: number, preset?: OutfitPreset) => {
    grid.forEach((row, gy) =>
      [...row].forEach((code, gx) => {
        if (code === "." || y + gy >= H || x + gx >= W) return;
        const slot = ["1", "2", "3"].indexOf(code);
        scene[y + gy]![x + gx] = slot >= 0 && preset ? OUTFIT_PRESETS[preset][slot]! : code;
      }),
    );
  };
  for (const [x, y, c] of [
    [12, 8, "w"],
    [40, 22, "y"],
    [70, 6, "w"],
    [96, 30, "w"],
    [118, 12, "y"],
    [140, 26, "w"],
    [176, 40, "w"],
    [190, 18, "y"],
    [58, 40, "w"],
    [26, 52, "w"],
  ] as const) {
    scene[y]![x] = c;
  }
  stamp(SCENE_SPRITES.moon, 160, 8);
  const ground = SCENE_SPRITES.ground;
  for (let x = 0; x < W; x += 16) stamp(ground, x, H - 16);
  const stand = H - 16 + 3; // props stand 3ap into the ground strip
  stamp(SCENE_SPRITES.bush, 92, stand - 16);
  stamp(SCENE_SPRITES["quest-board"], 106, stand - 32);
  stamp(SCENE_SPRITES["quest-marker"], 114, stand - 32 - 15);
  stamp(ADVENTURER.states.idle.frames[0]!, 138, stand - 31, "royal");
  stamp(SCENE_SPRITES.lantern, 170, stand - 32);
  stamp(SCENE_SPRITES.bush, 184, stand - 16);

  const grid = scene.map((row) => row.join(""));
  validateGrid("og-scene", grid, { w: W, h: H });
  const canvas = createCanvas(W * SCALE, H * SCALE);
  drawGrid(canvas, grid, 0, 0, { scale: SCALE });
  const png = encodePng(canvas);
  write("src/app/_og/og-scene.png", png);
  return png;
}

/** The scene plus its title text → the static link-preview image (scripts/art/og.tsx). */
async function buildOgImage(scene: Buffer) {
  const font = readFileSync(join(ROOT, "src/app/_og/Galmuri11.og.ttf"));
  write("src/app/opengraph-image.png", await renderOgImage(scene, font));
  write("src/app/opengraph-image.alt.txt", OG_ALT);
}

/* ───────── Palette ───────── */

function buildPalette() {
  const lines = LIFE_32.map(({ hex, name }) => {
    const v = Number.parseInt(hex.slice(1), 16);
    const rgb = [(v >> 16) & 0xff, (v >> 8) & 0xff, v & 0xff].map((c) => String(c).padStart(3));
    return `${rgb.join(" ")}\t${name}`;
  });
  write(
    "art/palette/life-32.gpl",
    `GIMP Palette\nName: LIFE-32\nColumns: 8\n#\n${lines.join("\n")}\n`,
  );
}

console.log("Building pixel art…");
buildCharacter();
buildIcons();
buildScene();
const scene = buildOgScene();
buildPalette();
buildOgImage(scene).then(() => console.log("Done."));
