/**
 * Builds pixel-art sources in /art into shippable 1× PNG sheets + typed manifests.
 *
 *   pnpm art:build
 *
 * Outputs (all committed):
 *   public/sprites/characters/<id>-<preset>.png   one sheet per outfit preset (rows = states)
 *   public/icons/icons.png, public/icons/glyphs.png
 *   src/components/game/character/sprite-sheets.generated.ts
 *   src/components/pixel/icons.generated.ts
 *   src/app/icon.png                               32×32 favicon (head crop, 2×)
 *   art/palette/life-32.gpl                        Aseprite/GIMP palette
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { ADVENTURER } from "../../art/characters/adventurer";
import { GLYPHS, ICONS } from "../../art/icons";
import { LIFE_32, OUTFIT_PRESETS, type OutfitPreset } from "../../art/palette";
import type { PixelGrid } from "../../art/types";
import { createCanvas, cropGrid, drawGrid, encodePng, padGrid, validateGrid } from "./lib";

const ROOT = join(import.meta.dirname, "..", "..");
const ICON_SIZE = 16;
const GLYPH_SIZE = 8;
const SHEET_COLUMNS = 8;
const GENERATED_HEADER = "// GENERATED by `pnpm art:build` from /art — do not edit by hand.\n";

function write(relativePath: string, contents: Buffer | string) {
  const path = join(ROOT, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  console.log(`  wrote ${relativePath}`);
}

/* ───────── Characters ───────── */

function buildCharacter() {
  const { id, frameSize, anchor, states } = ADVENTURER;
  const stateEntries = Object.entries(states);
  const maxFrames = Math.max(...stateEntries.map(([, s]) => s.frames.length));

  for (const [name, state] of stateEntries) {
    if (state.frames.length !== state.durations.length) {
      throw new Error(`${id}.${name}: frames and durations differ in length`);
    }
    state.frames.forEach((frame, i) => validateGrid(`${id}.${name}[${i}]`, frame, frameSize, true));
  }

  const images: Record<string, string> = {};
  for (const preset of Object.keys(OUTFIT_PRESETS) as OutfitPreset[]) {
    const canvas = createCanvas(frameSize.w * maxFrames, frameSize.h * stateEntries.length);
    stateEntries.forEach(([, state], row) => {
      state.frames.forEach((frame, col) =>
        drawGrid(canvas, frame, col * frameSize.w, row * frameSize.h, { preset }),
      );
    });
    const file = `/sprites/characters/${id}-${preset}.png`;
    write(join("public", file), encodePng(canvas));
    images[preset] = file;
  }

  const manifest = {
    id,
    frameSize,
    anchor,
    sheetSize: { w: frameSize.w * maxFrames, h: frameSize.h * stateEntries.length },
    images,
    states: Object.fromEntries(
      stateEntries.map(([name, s], row) => [
        name,
        {
          row,
          frames: s.frames.length,
          durations: s.durations,
          loop: s.loop,
          ...("next" in s && s.next ? { next: s.next } : {}),
        },
      ]),
    ),
  };

  write(
    "src/components/game/character/sprite-sheets.generated.ts",
    `${GENERATED_HEADER}
export const SPRITE_SHEETS = ${JSON.stringify({ [id]: manifest }, null, 2)} as const;

export type SpriteSheetId = keyof typeof SPRITE_SHEETS;
`,
  );

  // Favicon: head crop (rows 3–15, cols 9–22) centered in 16×16, rendered at 2×.
  const head = padGrid(cropGrid(states.idle.frames[0]!, 9, 3, 14, 13), 16, 16);
  const favicon = createCanvas(32, 32);
  drawGrid(favicon, head, 0, 0, { preset: "royal", scale: 2 });
  write("src/app/icon.png", encodePng(favicon));
}

/* ───────── Icons & glyphs ───────── */

function buildAtlas(
  label: string,
  entries: ReadonlyArray<readonly [string, PixelGrid]>,
  size: number,
  file: string,
) {
  entries.forEach(([name, grid]) => validateGrid(`${label}.${name}`, grid, { w: size, h: size }));
  const columns = Math.min(SHEET_COLUMNS, entries.length);
  const rows = Math.ceil(entries.length / columns);
  const canvas = createCanvas(columns * size, rows * size);
  entries.forEach(([, grid], i) =>
    drawGrid(canvas, grid, (i % columns) * size, Math.floor(i / columns) * size),
  );
  write(join("public", file), encodePng(canvas));
  return {
    src: file,
    size,
    columns,
    sheetSize: { w: columns * size, h: rows * size },
    names: entries.map(([name]) => name),
  };
}

function buildIcons() {
  const icons = buildAtlas("icon", Object.entries(ICONS), ICON_SIZE, "/icons/icons.png");
  const glyphs = buildAtlas("glyph", Object.entries(GLYPHS), GLYPH_SIZE, "/icons/glyphs.png");
  write(
    "src/components/pixel/icons.generated.ts",
    `${GENERATED_HEADER}
export const ICON_ATLAS = ${JSON.stringify(icons, null, 2)} as const;

export const GLYPH_ATLAS = ${JSON.stringify(glyphs, null, 2)} as const;

export type IconName = (typeof ICON_ATLAS.names)[number];
export type GlyphName = (typeof GLYPH_ATLAS.names)[number];
`,
  );
}

/* ───────── Palette ───────── */

function buildPalette() {
  const lines = LIFE_32.map(({ hex, name }) => {
    const v = Number.parseInt(hex.slice(1), 16);
    const rgb = [(v >> 16) & 0xff, (v >> 8) & 0xff, v & 0xff].map((c) => String(c).padStart(3));
    return `${rgb.join(" ")}\t${name}`;
  });
  write(
    "art/palette/life-32.gpl",
    `GIMP Palette\nName: LIFE-32\nColumns: 8\n#\n${lines.join("\n")}\n`,
  );
}

console.log("Building pixel art…");
buildCharacter();
buildIcons();
buildPalette();
console.log("Done.");
