// GENERATED by `pnpm art:build` from /art — do not edit by hand.

export const SPRITE_SHEETS = {
  "adventurer": {
    "id": "adventurer",
    "frameSize": {
      "w": 32,
      "h": 32
    },
    "anchor": {
      "x": 16,
      "y": 30
    },
    "sheetSize": {
      "w": 128,
      "h": 64
    },
    "images": {
      "royal": "/sprites/characters/adventurer-royal.png",
      "emerald": "/sprites/characters/adventurer-emerald.png",
      "violet": "/sprites/characters/adventurer-violet.png",
      "ember": "/sprites/characters/adventurer-ember.png"
    },
    "states": {
      "idle": {
        "row": 0,
        "frames": 4,
        "durations": [
          420,
          220,
          420,
          220
        ],
        "loop": true
      },
      "walking": {
        "row": 1,
        "frames": 4,
        "durations": [
          150,
          150,
          150,
          150
        ],
        "loop": true
      }
    }
  }
} as const;

export type SpriteSheetId = keyof typeof SPRITE_SHEETS;
